import Link from 'next/link';
import { Data, Entity, Row, dateLabel, entities, groupedMoney, isDelivered, labels, missionBalance, moneyLabel, routes, rowTitle, titles, today, weekEnd } from '../../lib/admin/model';
import s from './admin.module.css';
export function PageHeading({title,description,action}:{title:string;description?:string;action?:React.ReactNode}){return <div className={s.pageHeading}><div><p className={s.kicker}>Votre espace de travail</p><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</div>;}
export function AddLink({entity,client}:{entity:Entity;client?:string}){return <Link className={s.primary} href={`/admin/${routes[entity]}/nouveau${client?`?client=${client}`:''}`}>Ajouter {({clients:'un client',missions:'une mission',tasks:'une tâche',deliverables:'un livrable',payments:'un paiement',notes:'une note'})[entity]}</Link>;}
export function Empty({text='Aucun élément pour le moment.'}:{text?:string}){return <p className={s.empty}>{text}</p>;}
export function Badge({value}:{value:unknown}){const key=String(value||'');return key?<span className={`${s.badge} ${['retard','urgente'].includes(key)?s.warning:''}`}>{labels[key]||key}</span>:null;}
export function Records({entity,rows,data}:{entity:Entity;rows:Row[];data:Data}){
  if(!rows.length)return <Empty/>;
  return <ul className={s.records}>{rows.map(row=>{
    const client=data.clients.find(c=>c.id===row.client_id);
    const mission=data.missions.find(m=>m.id===row.mission_id);
    const detail=entity==='payments'?`${moneyLabel(Number(row.amount_cents),String(row.currency))} · ${dateLabel(row.paid_on)}`:rowTitle(row);
    return <li key={row.id}><div><Link className={s.recordTitle} href={`/admin/${routes[entity]}/${row.id}`}>{detail}</Link><p className={s.meta}>{entity==='clients'?(row.company||'Client indépendant'):[client&&rowTitle(client),mission&&rowTitle(mission)].filter(Boolean).join(' · ')||titles[entity]}</p>{row.due_date&&<small>Échéance : {dateLabel(row.due_date)}</small>}{entity==='deliverables'&&row.planned_on&&<small>Prévu le {dateLabel(row.planned_on)}</small>}</div><div className={s.recordEnd}><Badge value={row.status}/>{entity==='tasks'&&<Badge value={row.priority}/ >}{entity==='missions'&&<small>{moneyLabel(missionBalance(row,data.payments).remaining,String(row.currency))} à recevoir</small>}</div></li>;
  })}</ul>;
}
export function Balances({missions,data}:{missions:Row[];data:Data}){return missions.length?<ul className={s.records}>{missions.map(m=>{const b=missionBalance(m,data.payments);return <li key={m.id}><div><Link className={s.recordTitle} href={`/admin/missions/${m.id}`}>{rowTitle(m)}</Link><p className={s.meta}>{rowTitle(data.clients.find(c=>c.id===m.client_id)||m)} · Échéance : {dateLabel(m.due_date)}</p><small>Convenu : {moneyLabel(Number(m.amount_cents),String(m.currency))} · Reçu : {moneyLabel(b.paid,String(m.currency))}</small></div><div className={s.recordEnd}><strong>{moneyLabel(b.remaining,String(m.currency))}</strong><Badge value={b.status}/><Link href={`/admin/paiements/nouveau?client=${m.client_id}&mission=${m.id}`} className={s.textLink}>Enregistrer un paiement</Link></div></li>;})}</ul>:<Empty text="Aucun solde à suivre."/>;}
export function Dashboard({data}:{data:Data}){
 const day=today(),end=weekEnd(day);
 const outstanding=data.missions.filter(m=>missionBalance(m,data.payments,day).remaining>0);
 const received=data.payments.filter(p=>String(p.paid_on).startsWith(day.slice(0,7)));
 const activeTasks=data.tasks.filter(t=>t.status!=='termine');
 const late=activeTasks.filter(t=>t.due_date&&String(t.due_date)<day);
 const week=activeTasks.filter(t=>t.due_date&&String(t.due_date)>=day&&String(t.due_date)<=end).sort((a,b)=>String(a.due_date).localeCompare(String(b.due_date)));
 const soon=data.missions.filter(m=>m.status==='actif'&&m.end_date&&String(m.end_date)>=day&&String(m.end_date)<=end);
 const stats=[['Clients actifs',String(data.clients.filter(c=>c.status==='actif').length),'/admin/clients'],['À recevoir',groupedMoney(outstanding.map(m=>({currency:String(m.currency),amount:missionBalance(m,data.payments).remaining}))),'/admin/paiements?vue=solde'],['Reçu ce mois',groupedMoney(received.map(p=>({currency:String(p.currency),amount:Number(p.amount_cents)}))),'/admin/paiements?vue=mois'],['Tâches en cours',String(activeTasks.length),'/admin/taches?vue=actives'],['Tâches en retard',String(late.length),'/admin/taches?vue=retard'],['Livrables à produire',String(data.deliverables.filter(d=>!isDelivered(d)).length),'/admin/livrables?vue=restants']];
 return <><PageHeading title="Une vue claire sur votre activité." description={dateLabel(day)} action={<AddLink entity="clients"/>}/><div className={s.stats}>{stats.map(([label,value,href])=><Link href={href} key={label} className={s.stat}><span>{label}</span><strong>{value}</strong></Link>)}</div>{!data.clients.length&&<div className={s.panel}><h2>Commencez par votre premier client.</h2><p>Ajoutez ensuite sa mission et son montant convenu. Les tâches, livrables et paiements viendront s’y rattacher. Aucune entreprise de votre portfolio n’est importée automatiquement.</p></div>}<div className={s.columns}><section className={s.panel}><h2>À faire cette semaine</h2><Records entity="tasks" rows={week.slice(0,8)} data={data}/><Link className={s.textLink} href="/admin/taches?vue=semaine">Voir toute la semaine</Link>{late.length>0&&<p className={s.notice}>{late.length} tâche(s) en retard à consulter également.</p>}</section><section className={s.panel}><h2>Paiements à relancer</h2><Balances missions={outstanding.filter(m=>missionBalance(m,data.payments).status==='retard').slice(0,6)} data={data}/><Link className={s.textLink} href="/admin/paiements?vue=solde">Tous les soldes</Link></section></div><section className={s.panel}><h2>Missions se terminant cette semaine</h2><Records entity="missions" rows={soon} data={data}/></section></>;
}
export function Related({entity,row,data}:{entity:Entity;row:Row;data:Data}){
 if(entity!=='clients'&&entity!=='missions')return null;
 const match=(r:Row)=>entity==='clients'?r.client_id===row.id:r.mission_id===row.id;
 const missions=entity==='clients'?data.missions.filter(match):[row];
 const payments=data.payments.filter(match);
 return <><div className={s.stats}>{[['Montant convenu',groupedMoney(missions.map(m=>({currency:String(m.currency),amount:Number(m.amount_cents)})))],['Montant reçu',groupedMoney(payments.map(p=>({currency:String(p.currency),amount:Number(p.amount_cents)})))],['Solde restant',groupedMoney(missions.map(m=>({currency:String(m.currency),amount:missionBalance(m,data.payments).remaining}))) ]].map(([label,value])=><div className={s.stat} key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>{entities.filter(e=>e!=='clients'&&(entity==='clients'||e!=='missions')).map(e=><section className={s.panel} key={e}><div className={s.sectionHeading}><h2>{titles[e]}</h2><Link className={s.textLink} href={`/admin/${routes[e]}/nouveau?client=${entity==='clients'?row.id:row.client_id}${entity==='missions'?`&mission=${row.id}`:''}`}>Ajouter</Link></div><Records entity={e} rows={data[e].filter(match)} data={data}/></section>)}</>;
}
